server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  add-host-header: true
  sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长为5000ms
ribbon:
  ConnectionTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 3500 # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务器重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
ly:
  jwt:
    pubKeyPath:  G:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item